services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve & sleep 5 &&
       ollama pull gemma3:1b &&
       tail -f /dev/null"

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    container_name: desculpaai
    depends_on:
      - ollama
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  ollama_data:
