services:
  ollama:
    build:
      context: ./
      dockerfile: ./ollama/Dockerfile.app
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  goatcounter:
    build:
      context: ./
      dockerfile: ./goatcounter/Dockerfile.app
    container_name: goatcounter
    ports:
      - "8081:8080"
    volumes:
      - goatcounter_data:/home/goatcounter/goatcounter-data
    restart: unless-stopped

  desculpaai:
    build:
      context: ./
      dockerfile: ./desculpa-ai/Dockerfile.app
    container_name: desculpaai
    env_file:
      - .env
    depends_on:
      - ollama
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      PORT: 8080

volumes:
  ollama_data:
  goatcounter_data:
