# fly.toml app configuration file generated for goatcounter-desculpa-ai on 2025-08-26T15:49:38-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'goatcounter-desculpa-ai'
primary_region = 'gru'

[build]
  dockerfile = 'goatcounter/docker-compose'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
