app = "desculpa-ai"
primary_region = "gru"

[build]
dockerfile = "docker/Dockerfile.app"

[env]
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_start_machines = true
auto_stop_machines = "stop"
min_machines_running = 0

[[http_service.checks]]
interval = "30s"
timeout = "5s"
grace_period = "10s"
method = "GET"
path = "/"
protocol = "http"
