app = "goatcounter-desculpa-ai"
primary_region = "gru"

[build]
dockerfile = "./Dockerfile.app"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "256mb"
cpu_kind = "shared"
cpus = 1

[mounts]
source = "goatcounter_data"
destination = "/home/goatcounter"
